# Generated by Django 5.0.6 on 2024-07-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://th.bing.com/th/id/R.02f7af6e3d1936ba187a34063866a2a3?rik=DZviH5IohIQWdA&pid=ImgRaw&r=0', max_length=500),
        ),
    ]
