# Generated by Django 5.0.6 on 2024-07-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_image',
        ),
    ]
